version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      -./clickhouse/data:/var/lib/clickhouse
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '4g'

  postgres:
    image: postgres:latest
    container_name: postgres-server
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      -./postgresql/data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '4g'
